version: '2'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=wordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    ports:
      - 33309:3306
  wordpress:
    depends_on:
      - db
    image: share:latest
    links:
      - db
    ports:
      - 8081:80
    restart: always
    environment:
      - SHARE_DB_NAME=wordpress
      - SHARE_DB_USER=wordpress
      - SHARE_DB_PASSWORD=wordpress
      - SHARE_DB_HOST=db
      - SHARE_AUTH_KEY=test
      - SHARE_SECURE_AUTH_KEY=test
      - SHARE_LOGGED_IN_KEY=test
      - SHARE_NONCE_KEY=test
      - SHARE_AUTH_SALT=test
      - SHARE_SECURE_AUTH_SALT=test
      - SHARE_LOGGED_IN_SALT=test
      - SHARE_NONCE_SALT=test
      - SHARE_DOMAIN_CURRENT_SITE=share.america.dev
    volumes_from:
      - container:sharevolume

volumes:
  sharevolume:
    external: true

